# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Jeff Dahan - MS Internal (9a076c3b-efe6-41fc-8586-f2143f2ad975)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'aks-deploy.sh'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

